spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      # 어플리케이션 실행 시점에 가진 테이블을 모두 지우고 새로 생성한다.
      ddl-auto: create
      properties:
        hibernate:
#          show_sql: true
          format_sql: true

logging:
  level:
    # JPA나 hibernate가 생성하는 SQL이 다 보인다.
    # 위의 show_sql은 system.out으로 찍고 org.hibernate.SQL은 로그로 찍는다.
    org.hibernate.SQL: debug
    # 쿼리 파라미터의 타입을 알려준다.
    org.hibernate.type: trace